// Generated by CoffeeScript 1.8.0
(function() {
  var fs, main;

  fs = require('fs');

  main = function() {
    return console.log('main');
  };

  main();

}).call(this);

//# sourceMappingURL=main.js.map
